namespace Isite.Config
{
    public static class Settings
    {

        private static string settings = @"{
        'isite::offline':{
            'name':'isite::offline', 
            'value': '1', 
            'type': 'select', 
            'groupName': 'cms', 
            'groupTitle': 'isite::common.settingGroups.cms', 
            'props': { 
                'label': 'isite::common.settings.cms.offline', 
                'options' : [        
                    {'label': 'isite::common.yes', 'value': '1'},        
                    {'label': 'isite::common.no', 'value': '0'},      
                ]    
            },  
        },
        'isite::enableDynamicFieldsCache':{
            'name':'isite::enableDynamicFieldsCache', 
            'value': '1', 
            'type': 'select', 
            'groupName': 'cms', 
            'groupTitle': 'isite::common.settingGroups.cms', 
            'props': { 
                'label': 'isite::common.settings.cms.enableDynamicFieldsCache', 
                'options' : [        
                    {'label': 'isite::common.yes', 'value': '1'},        
                    {'label': 'isite::common.no', 'value': '0'},      
                ]    
            },  
        }, 
        'isite::legacyStructureCMS':{
            'name':'isite::legacyStructureCMS', 
            'value': '1', 
            'type': 'select', 
            'groupName': 'cms', 
            'groupTitle': 'isite::common.settingGroups.cms', 
            'props': { 
                'label': 'isite::common.settings.cms.legacyStructureCMS', 
                'options' : [        
                    {'label': 'isite::common.yes', 'value': '1'},        
                    {'label': 'isite::common.no', 'value': '0'},      
                ]    
            },  
        }, 
        'isite::secondaryContrast':{
            'onlySuperAdmin': false,
            'description': '',
            'default': null,
            'view': 'settingField',
            'translatable': false,
            'id': 44,
            'name': 'isite::secondaryContrast',
            'plainValue': '#ffffff',
            'isTranslatable': false,
            'created_at': '2022-04-21T18:26:06.000000Z',
            'updated_at': '2022-04-21T18:26:24.000000Z',
            'deleted_at': null,
            'created_by': null,
            'updated_by': null,
            'deleted_by': null,
            'organization_id': null,
            'value': '#ffffff',
            'translations': [ ]
        },
        'isite::primaryContrast':{
            'onlySuperAdmin': false,
            'description': '',
            'default': null,
            'view': 'settingField',
            'translatable': false,
            'id': 43,
            'name': 'isite::primaryContrast',
            'plainValue': '#ffffff',
            'isTranslatable': false,
            'created_at': '2022-04-21T18:26:06.000000Z',
            'updated_at': '2022-04-21T18:26:06.000000Z',
            'deleted_at': null,
            'created_by': null,
            'updated_by': null,
            'deleted_by': null,
            'organization_id': null,
            'value': '#ffffff',
            'translations': [ ]
        },
        'isite::iadminTheme':{
            'onlySuperAdmin': false,
            'description': '',
            'default': '1',
            'view': 'settingField',
            'translatable': false,
            'id': 42,
            'name': 'isite::iadminTheme',
            'plainValue': '2',
            'isTranslatable': false,
            'created_at': '2022-04-21T18:24:26.000000Z',
            'updated_at': '2022-04-21T18:24:26.000000Z',
            'deleted_at': null,
            'created_by': null,
            'updated_by': null,
            'deleted_by': null,
            'organization_id': null,
            'value': '2',
            'translations': []
        },
        'isite::appVersion':{
            'description':'',
            'default':'0.0.1',
            'view':'settingField',
            'translatable':false,
            'id':38,
            'name':'isite::appVersion',
            'plainValue':'0.0.1',
            'isTranslatable':false,
            'created_at':'2022-04-06T22:13:19.000000Z',
            'updated_at':'2022-04-06T22:13:19.000000Z',
            'value':'0.0.1',
            'translations':[]
        },
        'isite::logo1':{
            'description':'',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'id':3,
            'name':'isite::logo1',
            'plainValue':{'medias_single':{}},
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':{'medias_single':{}},
            'translations':[]
            ,'media':{
            'mimeType':'image/jpeg',
            'path':'https://agidev.blob.core.windows.net/agione/AGI_logo_app.png'}
        },
        'isite::logo2':{
            'description':'',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'id':4,
            'name':'isite::logo2',
            'plainValue':{'medias_single':{}},
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':{'medias_single':{}},
            'translations':[],
            'media':{'mimeType':'image/jpeg','path':'https://agidev.blob.core.windows.net/agione/AGI_logo_app.png'}
        },
        'isite::logo3':{
            'description':'',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'id':5,
            'name':'isite::logo3',
            'plainValue':{'medias_single':{}},
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':{'medias_single':{}},
            'translations':[],
            'media':{'mimeType':'image/jpeg','path':'https://agidev.blob.core.windows.net/agione/AGI_logo_app.png'}
        },
        'isite::logoIadmin':{
            'description':'Logo Iadmin',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'name':'isite::logoIadmin',
            'isTranslatable':false,
            'plainValue':{'medias_single':{}},
            'value':{'medias_single':{}},
            'media':{'mimeType':'image/jpeg','path':'https://agidev.blob.core.windows.net/agione/AGI_logo_app.png'}
        },
        'isite::favicon':{
            'description':'Favicon',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'name':'isite::favicon',
            'isTranslatable':false,
            'plainValue':{'medias_single':{}},
            'value':{'medias_single':{}},
            'media':{'mimeType':'image/jpeg','path':'https://agidev.blob.core.windows.net/agione/favicon-32x32.jpg'}
        },
        'isite::brandAddressBar':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':6,
            'name':'isite::brandAddressBar',
            'plainValue':'#027be3',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'#027be3',
            'translations':[]
        },
        'isite::brandPrimary':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':7,
            'name':'isite::brandPrimary',
            'plainValue':'#28489a',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'#28489a',
            'translations':[]
        },
        'isite::brandSecondary':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':8,
            'name':'isite::brandSecondary',
            'plainValue':'#4882eb',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'#4882eb',
            'translations':[]
        },
        'isite::brandAccent':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':9,
            'name':'isite::brandAccent',
            'plainValue':'#9c27b0',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'#9c27b0',
            'translations':[]
        },
        'isite::brandPositive':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':10,
            'name':'isite::brandPositive',
            'plainValue':'#21ba45',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'#21ba45',
            'translations':[]
        },
        'isite::brandNegative':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':11,
            'name':'isite::brandNegative',
            'plainValue':'#c10015',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'#c10015',
            'translations':[]
        },
        'isite::brandInfo':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':12,
            'name':'isite::brandInfo',
            'plainValue':'#31ccec',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'#31ccec',
            'translations':[]
        },
        'isite::brandWarning':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':13,
            'name':'isite::brandWarning',
            'plainValue':'#f2c037',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'#f2c037',
            'translations':[]
        },
        'isite::brandDark':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':14,
            'name':'isite::brandDark',
            'plainValue':'#1d1d1d',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'#1d1d1d',
            'translations':[]
        },
        'isite::activateCaptcha':{
            'description':'',
            'default':'0',
            'view':'settingField',
            'translatable':false,
            'id':28,
            'name':'isite::activateCaptcha',
            'plainValue':'0',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'value':'0',
            'translations':[]
        },
        'isite::reCaptchaV2Secret':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':29,
            'name':'isite::reCaptchaV2Secret',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'translations':[]
        },
        'isite::reCaptchaV2Site':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':30,
            'name':'isite::reCaptchaV2Site',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'translations':[]
        },
        'isite::reCaptchaV3Secret':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':31,
            'name':'isite::reCaptchaV3Secret',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'translations':[]
        },
        'isite::reCaptchaV3Site':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':32,
            'name':'isite::reCaptchaV3Site',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'translations':[]
        },
        'isite::api-maps':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':33,
            'name':'isite::api-maps',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'translations':[]
        },
        'isite::api-open-street-maps':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':34,
            'name':'isite::api-open-street-maps',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'translations':[]
        },
        'isite::phones':{
            'description':'Teléfonos',
            'default':'[]',
            'view':'settingField',
            'translatable':false,
            'name':'isite::phones',
            'isTranslatable':false,
            'plainValue':[],
            'value':[]
        },
        'isite::addresses':{
            'description':'Direcciones',
            'default':'[]',
            'view':'settingField',
            'translatable':false,
            'name':'isite::addresses',
            'isTranslatable':false,
            'plainValue':[],
            'value':[]
        },
        'isite::emails':{
            'description':'Correos',
            'default':'[]',
            'view':'settingField',
            'translatable':false,
            'name':'isite::emails',
            'isTranslatable':false,
            'plainValue':[],
            'value':[]
        },
        'isite::headerCustomJs':{
            'description':'JS Personalizado para el Head',
            'view':'settingField',
            'translatable':false,
            'name':'isite::headerCustomJs',
            'isTranslatable':false
        },
        'isite::customCss':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':15,
            'name':'isite::customCss',
            'plainValue':'',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'',
            'translations':[]
        },
        'isite::customJs':{
            'description':'',
            'view':'settingField',
            'translatable':false,
            'id':16,
            'name':'isite::customJs',
            'plainValue':'',
            'isTranslatable':false,
            'created_at':'2021-11-25T21:25:01.000000Z',
            'updated_at':'2021-11-25T21:25:01.000000Z',
            'value':'',
            'translations':[]
        },
        'isite::googleClientId':{
            'description':'',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'id':35,
            'name':'isite::googleClientId',
            'plainValue':'',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'value':'',
            'translations':[]
        },
        'isite::facebookClientId':{
            'description':'',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'id':36,
            'name':'isite::facebookClientId',
            'plainValue':'',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'value':'',
            'translations':[]
        },
        'isite::facebookAppId':{
            'description':'',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'id':37,
            'name':'isite::facebookAppId',
            'plainValue':'',
            'isTranslatable':false,
            'created_at':'2022-03-01T22:55:02.000000Z',
            'updated_at':'2022-03-01T22:55:02.000000Z',
            'value':'',
            'translations':[]
        },
        'isite::pdfLogoHeader':{
            'description':'Elige el logo que quieres que aparezca en el pdf',
            'default':'logo1',
            'view':'settingField',
            'translatable':false,
            'name':'isite::pdfLogoHeader',
            'isTranslatable':false,
            'plainValue':'logo1',
            'value':'logo1'
        },
        'isite::pdfPreContent':{
            'description':'Agregue contenido informativo que aparecerá en el encabezado del pdf',
            'view':'settingField',
            'translatable':false,
            'name':'isite::pdfPreContent',
            'isTranslatable':false
        },
        'isite::pdfFooterContent':{
            'description':'Agregue contenido informativo que aparecerá en el pie de página del pdf',
            'view':'settingField',
            'translatable':false,
            'name':'isite::pdfFooterContent',
            'isTranslatable':false
        },
        'isite::pdfPostContent':{
            'description':'Agregar información sobre el contenido del pdf (no perteneciente a una tienda)',
            'view':'settingField',
            'translatable':false,
            'name':'isite::pdfPostContent',
            'isTranslatable':false
        },
        'isite::rolesToTenant':{
            'description':'Roles habilitados como inquilinos',
            'default':'[]',
            'view':'settingField',
            'translatable':false,
            'name':'isite::rolesToTenant',
            'isTranslatable':false,
            'plainValue':[],
            'value':[]
        },
        'isite::tenantRouteAlias':{
            'description':'Alias de la ruta de aterrizaje para los Inquilinos',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'name':'isite::tenantRouteAlias',
            'isTranslatable':false,
            'plainValue':'',
            'value':''
        },
        'isite::mapInShow':{
            'description':'Mapas en el sitio',
            'default':'openStreet',
            'view':'settingField',
            'translatable':false,
            'name':'isite::mapInShow',
            'isTranslatable':false,
            'plainValue':'openStreet',
            'value':'openStreet'
        },
        'isite::statusModalVerifier':{
            'description':'Activar',
            'default':'0',
            'view':'settingField',
            'translatable':false,
            'name':'isite::statusModalVerifier',
            'isTranslatable':false,
            'plainValue':'0',
            'value':'0'
        },
        'isite::titleModalVerifier':{
            'description':'Título',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'name':'isite::titleModalVerifier',
            'isTranslatable':false,
            'plainValue':'',
            'value':''
        },
            'isite::contentModalVerifier':{
            'description':'Contenido',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'name':'isite::contentModalVerifier',
            'isTranslatable':false,
            'plainValue':'',
            'value':''
        },
            'isite::buttonLabelModalVerifier':{
            'description':'Texto del botón',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'name':'isite::buttonLabelModalVerifier',
            'isTranslatable':false,
            'plainValue':'',
            'value':''
        },
            'isite::headerLayout':{
            'description':'',
            'default':'header-layout-1',
            'view':'settingField',
            'translatable':false,
            'id':39,
            'name':'isite::headerLayout',
            'plainValue':'header-layout-1',
            'isTranslatable':false,
            'created_at':'2022-04-06T22:13:19.000000Z',
            'updated_at':'2022-04-06T22:13:19.000000Z',
            'value':'header-layout-1',
            'translations':[]
        },
            'isite::footerLayout':{
            'description':'',
            'default':'footer-layout-1',
            'view':'settingField',
            'translatable':false,
            'id':40,
            'name':'isite::footerLayout',
            'plainValue':'footer-layout-1',
            'isTranslatable':false,
            'created_at':'2022-04-06T22:13:19.000000Z',
            'updated_at':'2022-04-06T22:13:19.000000Z',
            'value':'footer-layout-1',
            'translations':[]
        },
            'isite::itemsTabs':{
            'description':'Ingresa Titulos para los tabs',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'name':'isite::itemsTabs',
            'isTranslatable':false,
            'plainValue':['Item-1','Item-2'],
            'value':['Item-1','Item-2']
        },
            'isite::locationSite':{
            'description':'Ubicación Sede Principal',
            'default':'',
            'view':'settingField',
            'translatable':false,
            'name':'isite::locationSite',
            'isTranslatable':false,
            'plainValue':'',
            'value':''
        },
            'isite::tenantWithCentralData':{
            'description':'Entidades con data central',
            'default':'[]',
            'view':'settingField',
            'translatable':false,
            'name':'isite::tenantWithCentralData',
            'isTranslatable':false,
            'plainValue':[],
            'value':[]
        },
            'isite::legacyStructureCMS':{
            'description':'',
            'default':'0',
            'view':'settingField',
            'translatable':false,
            'id':41,
            'name':'isite::legacyStructureCMS',
            'plainValue':'1',
            'isTranslatable':false,
            'created_at':'2022-04-06T22:13:19.000000Z',
            'updated_at':'2022-04-06T22:13:19.000000Z',
            'value':'1',
            'translations':[]
        },
        'isite::microsoftClientId':{
            'default': '',
            'description': 'Cliente Microsoft',
            'isTranslatable': false,
            'name': 'isite::microsoftClientId',
            'onlySuperAdmin': false,
            'plainValue': '43331c90-0692-47a9-a48f-662f1bbf9c3e',
            'translatable': false,
            'value': '43331c90-0692-47a9-a48f-662f1bbf9c3e',
            'view': 'settingField'
        }
        }";

        public static string GetSettings()
        {
            return settings;
        }
    }
}
